### PR TITLE
Long Stack Trace Support

### LINKED ISSUE #2: Support promise long stack traces
Currently this:
```
Error: e
    at null._onTimeout (/Users/jamestalmage/WebstormProjects/stack-utils/foo.js:27:11)
    at Timer.listOnTimeout (timers.js:119:15)
From previous event:
    at /Users/jamestalmage/WebstormProjects/stack-utils/foo.js:25:9
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at Object.<anonymous> (/Users/jamestalmage/WebstormProjects/stack-utils/foo.js:24:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

becomes this

```
null._onTimeout (foo.js:27:11)
From previous event:
foo.js:25:9
From previous event:
Object.<anonymous> (foo.js:24:3)
node.js:814:3
```

Pretty good, but it It would be better if the cleaned stack trace kept some form of indentation between the `From previous event` lines.

I am not sure the best way to detect this, just look for `From previous event`? This example is `bluebird`, but I know  `q` and others support the same idea, but I'm not sure how they format it.

Would it just be better to look for unindented separator lines? That may cover a wider range of implementations, but are normal stack trace lines always guaranteed to be indented?

// @sindresorhus @isaacs

### PR DESCRIPTION
**Pull request by jamestalmage**
Fixes #2 

This creates two sets of fixtures:

- One uses both `bluebird` and `Q` to generate promise long stack traces with `From previous event:` lines.
- The other uses `nested-error-stacks` to create long stack traces with `Caused By...` lines.

Indentation is removed from all lines until the first separator line is found.

If all `    at ` lines are removed in a given section, then the separator line is also removed (not sure if this is the right thing to do, but I think it is).

Reviewers: @isaacs @sindresorhus

### CODE REVIEW

File: test/long-stack-traces.js [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+function internals() {
+	return StackUtils.nodeInternals().concat([
+		/[\\\/]long-stack-traces\.js:[0-9]+:[0-9]+\)?$/,
+		/[\\\/]internal-error\.js:[0-9]+:[0-9]+\)?$/,
+		/[\\\/]internal-then\.js:[0-9]+:[0-9]+\)?$/,
+		/[\\\/]node_modules[\\\/]/,
+		// TODO: Should any of these be default internals?
+		/[\\\/]\.node-spawn-wrap-\w+-\w+[\\\/]node:[0-9]+:[0-9]+\)?$/,
+		/internal[\\\/]module\.js:[0-9]+:[0-9]+\)?$/,
+		/node\.js:[0-9]+:[0-9]+\)?$/
```
Comment (jamestalmage) [inline test/long-stack-traces.js]: I think the above three lines should be part of the default internals.

The `spawn-wrap` is a bit iffy, but I doubt anyone actually wants that
